### PR TITLE
Initial Implement

### PR DESCRIPTION
**Pull request by soasme**
- Borrow some of SRL-PHP implement in Builder
- Parser is written via `lex` + `yacc` with vendoring `ply`
- SRL(srl_string) is a Python `re.RegexObject` API-compatible instance

---

TODO:
- [x] finishing all the test cases supplied in Test-Rules.

### CODE REVIEW

**Comment by KarimGeiger** [comment]
Great work, @soasme! If you're ready, feel free to merge this pull request. I'm happy to then link to this project on simple-regex.com as an official implementation, since it seems to work quite good.

**Comment by soasme** [comment]
@KarimGeiger  I have some questions.
- According to the [document](https://simple-regex.com/documentation/quantifiers), it should be `times` as part of quantifier. But it's `time` in the rule test supplied. So I let`times|time` both work.
- Should I follow the naming convention of CamelCase?
- The Builder/Match API is not documented. Is it better to have a standard API as well?

**Comment by KarimGeiger** [comment]
- Yes, that's correct. Both `exactly 1 time` as well as `exactly 2 times` should be valid.
- No, you don't have to. If there is, try following the Python naming convention.
- That's a part I'm not quite sure about yet. I think I'm going to request this in the language documentation later on, but currently it's optional. The problem I'm having with that is that regular expressions are implemented in different ways in each language. So it might make sense to stick to these features. JavaScript for example handles them quite well, so I'd say they don't need a wrapper for that. PHP does it badly (in my opinion), so I wrote a wrapper for it.
  To begin with, I'd say: Do however you like. If you think it makes sense to build a match wrapper, go for it. If not, it can be added later, if necessary.

**Comment by SaptakS** [comment]
@soasme @KarimGeiger according to PEP-8, the naming convention used for variables and functions is snake_case.. But I think naming convention mostly depends on us and should be maintained throughout. So, either of the 2 naming convention is fine I think.

**Comment by KarimGeiger** [comment]
In that case I'd go with snake_case, since it's commonly used in Python if defined in PEP-8.

**Comment by soasme** [comment]
SRL instance has no defined methods but forwards all method calls to a compiled `re.RegexObject`. So it follows Python regex convention in this case. If there is going to follow a unified Builder API, it can be easily to be added. Currently, I prefer to treat `Builder` as internal implement.

**Comment by soasme** [comment]
@KarimGeiger I have added `.travis.yml` in this PR. Please activate this repository in [travis](https://travis-ci.org/SimpleRegex/SRL-Python). Thanks!

**Comment by KarimGeiger** [comment]
Awesome! Travis is activated.

**Pull request merged**
